### ISSUE TITLE
Helm charts need a PVC for Search Repeater

### ISSUE THREAD

**Issue by b-douglas** [IBM/wc-helmchart#4]
They Helm Charts need a Persistent Volume claim for Search Repeater.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.Common.Tenant }}{{ .Values.Common.Environment_name}}-search-repeater-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
